"""grouping reservations by range

Revision ID: d6a0aa382fac
Revises: ab8095304c83
Create Date: 2021-01-28 13:45:36.429865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a0aa382fac'
down_revision = 'ab8095304c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('date_range', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'date_range')
    # ### end Alembic commands ###
