"""add state

Revision ID: 04346a918f6d
Revises: d6a0aa382fac
Create Date: 2021-01-29 11:22:30.922945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04346a918f6d'
down_revision = 'd6a0aa382fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'state')
    # ### end Alembic commands ###
