"""new reservation

Revision ID: ab8095304c83
Revises: d6d454d8f70d
Create Date: 2021-01-28 11:34:43.172055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8095304c83'
down_revision = 'd6d454d8f70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('numGuests', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'numGuests')
    # ### end Alembic commands ###
